name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: delete the package-lock.json
      run: cd frontend && rm -rf package-lock.json

    - name: install frontend 
      run:  cd frontend && npm install
      
    - name: install fronted react-script
      run: cd frontend && npm install -g create-react-app
      
    - name: Install frontend dependencies
      run:  cd frontend && npm install -D
      
    - name: Intsall frontend dev dependencies
      run: cd frontend && npm install -P
      
   
      
    - name: Install dependencies
      run:  npm install     

    - name: Run the tests
      run: cd frontend && npm test

    - name: Build
      run: cd frontend && npm run build
      
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "seeds-2021" #Must be unique in Heroku
        heroku_email: "njm7162@autuni.ac.nz"
